source "http://rubygems.org"

gem 'thin'
gem 'sinatra'
gem 'cf-runtime'
gem 'data_mapper'
gem 'amqp'

group :development do
  gem 'dm-sqlite-adapter'
end

group :production do
  gem 'dm-mysql-adapter'
end
